-- Amalgamate curse's runtime modules into ONE precompiled-bytecode bundle, so a
-- fresh process loads it with a single file open and zero source parsing. This is
-- the ~1ms/invocation startup win the benchmarks pointed at: LuaJIT parsing our
-- ~1600 lines of source on every start costs ~1.35ms; loading bytecode is ~0.37ms.
--
-- Bytecode is version/arch-specific, which is fine here: the bundle is REGENERATED
-- by this build for the exact LuaJIT it ships with (producer == consumer), so the
-- fragility that rules bytecode out for a portable cache doesn't apply. Run:
--   luajit lua/build.lua [dist/curse.bc]
-- CORE modules: needed by essentially any script, so embedded as nested closures
-- that the single bundle chunk bcreads in one fast pass at startup.
-- `run` is lua/run.lua — the sh CLI entry (`-c CODE`, `script args`, `-i`, options).
-- It's a script, not a return-module, so requiring it EXECUTES the shell (reading the
-- global `arg` the static binary's luajit.c sets up) and os.exit()s. Bundling it lets
-- the self-contained static binary BE /bin/sh: pmain, when invoked as a shell name,
-- does require("run"). The dynamic dev binary loads run.lua as a file instead, so this
-- preload entry just rides along unused there.
local mods = { "runtime", "parser", "emit", "interp", "tier", "cache", "repl", "run" }

-- FEATURE modules: embedded in the SAME unified bundle but bcread LAZILY — their
-- bytecode rides along as a string constant (copied, not proto-parsed, at startup)
-- and only turns into functions when a script first require()s the feature. A cold
-- simple script (which touches ~7% of the interpreter) never pays for them. require
-- caches in package.loaded, so a feature loads at most once. Files: lua/<name>.lua.
local lazy_mods = {
	"b_echo",
	"b_completion",
	"b_ulimit",
	"b_times",
	"b_alias",
	"b_unalias",
	"b_umask",
	"b_getopts",
	"b_hash",
	"b_history",
	"b_jobs",
	"b_trap",
	"b_type",
	"b_printf",
	"b_read",
	"b_mapfile",
	"b_export",
	"b_cd",
	"b_unset",
	"b_set",
	"b_eval",
	"b_source",
	"b_wait",
	"b_fg",
	"b_fc",
	"b_bind",
	"b_shopt",
	"b_let",
	"b_kill",
	"b_pushd",
	"b_builtin",
	"b_pwd",
	"b_shift",
	"b_local",
	"b_help",
	"deparse", -- function printing (declare -f / type): only when something is printed
}

-- Wrap each core module's source in a package.preload closure. `require("x")` then
-- resolves from memory with no file I/O and no parse. Registration is lazy, so
-- inter-module requires resolve fine regardless of order.
local parts = {}
for _, m in ipairs(mods) do
	local f = assert(io.open("lua/" .. m .. ".lua", "r"))
	local s = f:read("*a")
	f:close()
	parts[#parts + 1] = ("package.preload[%q] = function(...)\n%s\nend\n"):format(m, s)
end
-- Each lazy feature module's bytecode as an escaped string constant + a preload
-- loader that bcreads it on demand.
local function esc(s)
	return (s:gsub(".", function(c)
		return "\\" .. c:byte()
	end))
end
for _, m in ipairs(lazy_mods) do
	local f = assert(io.open("lua/" .. m .. ".lua", "r"))
	local s = f:read("*a")
	f:close()
	local mbc = string.dump(assert(loadstring(s, "=" .. m)))
	parts[#parts + 1] = ('package.preload[%q] = function(...) return assert(loadstring("%s", "=%s"))(...) end\n'):format(
		m,
		esc(mbc),
		m
	)
end
-- The build's identity for the compile cache (cache.lua): a content hash of everything
-- bundled, so artifacts from a different build are clean misses, never miscompiles.
do
	local ffi = require("ffi")
	local u64 = ffi.typeof("uint64_t")
	local h, prime = u64(14695981039346656037ULL), u64(1099511628211ULL)
	for i = 1, #parts do
		local s = parts[i]
		local p = ffi.cast("const uint8_t*", s)
		for k = 0, #s - 1 do
			h = bit.bxor(h, u64(p[k])) * prime
		end
	end
	table.insert(parts, 1, ("package.preload[\"curse_buildid\"] = function() return %q end\n"):format(bit.tohex(h)))
end
local bundle_src = table.concat(parts)

local chunk = assert(loadstring(bundle_src, "=curse.bundle"))
local bc = string.dump(chunk) -- keep debug info: line-accurate tracebacks in our runtime

local dest = arg[1] or "dist/curse.bc"
local dir = dest:match("^(.*)/[^/]+$")
if dir then
	os.execute("mkdir -p " .. dir)
end
local o = assert(io.open(dest, "w"))
o:write(bc)
o:close()
print(("wrote %s (%d modules, %d bytes bytecode)"):format(dest, #mods, #bc))

-- Second arg: also emit the bytecode as a C source embedding it in the binary
-- (linked into luajit for a self-contained static build; loaded by
-- curse_load_bundle in luajit.c). Kept opt-in so the default build stays fast.
local cdest = arg[2]
if cdest then
	local parts2 = {
		"/* GENERATED by lua/build.lua -- curse module bundle as embeddable bytecode */\n",
		("const unsigned int curse_bundle_bc_len = %d;\n"):format(#bc),
		"const unsigned char curse_bundle_bc[] = {\n",
	}
	local line = {}
	for i = 1, #bc do
		line[#line + 1] = tostring(bc:byte(i))
		if #line == 24 then
			parts2[#parts2 + 1] = table.concat(line, ",") .. ",\n"
			line = {}
		end
	end
	if #line > 0 then
		parts2[#parts2 + 1] = table.concat(line, ",") .. ",\n"
	end
	parts2[#parts2 + 1] = "};\n"
	local c = assert(io.open(cdest, "w"))
	c:write(table.concat(parts2))
	c:close()
	print(("wrote %s (%d bytes as C array)"):format(cdest, #bc))
end
