/* AOT emitter: lower a command tree into a standalone `.mts` module.
 *
 * M0 lowers connection structure into native TypeScript control flow and
 * defers word-level semantics (expansion, splitting, quoting) to the runtime
 * via `sh.simpleRaw(rawWords)`. Later milestones push more into the emitted
 * code (literal argv, inlined arithmetic, etc.) for readability and speed.
 *
 * Every command leaves its exit status in `sh.status` (bash's `$?`), which is
 * how `&&` / `||` chain — exactly as the interpreter does. */

import type { Command } from "../ast/nodes.mts";

export interface EmitOptions {
  /** Import specifier (path or file: URL) for the runtime's `Shell`. */
  runtimeSpecifier: string;
}

const pad = (n: number): string => "  ".repeat(n);

const emitCommand = (cmd: Command, ind: number): string => {
  switch (cmd.type) {
    case "simple": {
      const words = cmd.words.map((w) => JSON.stringify(w.text)).join(", ");
      return `${pad(ind)}await sh.simpleRaw([${words}]);`;
    }
    case "connection": {
      if (cmd.connector === ";") {
        return emitCommand(cmd.first, ind) + "\n" + emitCommand(cmd.second, ind);
      }
      if (cmd.connector === "&&" || cmd.connector === "||") {
        const test = cmd.connector === "&&" ? "=== 0" : "!== 0";
        return (
          emitCommand(cmd.first, ind) + "\n" +
          `${pad(ind)}if (sh.status ${test}) {\n` +
          emitCommand(cmd.second, ind + 1) + "\n" +
          `${pad(ind)}}`
        );
      }
      throw new Error(`connector \`${cmd.connector}\` not supported yet`);
    }
    default:
      throw new Error(`command type \`${cmd.type}\` not supported yet`);
  }
};

export const emit = (cmd: Command | null, opts: EmitOptions): string => {
  const body = cmd === null ? "" : emitCommand(cmd, 0) + "\n";
  return (
    "// Generated by curse. Do not edit.\n" +
    `import { Shell } from ${JSON.stringify(opts.runtimeSpecifier)};\n` +
    "\n" +
    "const sh = new Shell();\n" +
    body +
    "process.exitCode = sh.status;\n"
  );
};
