[ 5 -gt 3 ] && echo "5>3"
[ 5 -lt 3 ] || echo "not 5<3"
[ "abc" = "abc" ] && echo "eq"
[ "abc" != "xyz" ] && echo "ne"
[ -n "nonempty" ] && echo "nonempty"
[ -z "" ] && echo "zero"
[ 2 -eq 2 -a 3 -eq 3 ] && echo "both"
[ 1 -eq 2 -o 3 -eq 3 ] && echo "either"
test 4 -gt 2 && echo "test works"
